name: Dev Build Meshtastic Heltec v3 OLED_RU

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 2 * * *"   # run daily at 02:00 UTC
  workflow_dispatch:        # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: |
          pip install -U pip
          pip install platformio

      - name: Fetch Meshtastic firmware
        run: |
          git clone --depth=1 --recurse-submodules https://github.com/meshtastic/firmware.git
          cd firmware
          git checkout develop  

      - name: Debug paths
        run: |
          cd firmware
          ls -R

      - name: Patch platformio.ini for OLED_RU
        run: |
          sed -i '/-I variants\/esp32s3\/heltec_v3/a\  -D OLED_RU' variants/esp32s3/heltec_v3/platformio.ini
        
      - name: Build Heltec V3 firmware
        run: |
          cd firmware
          pio run -e heltec-v3

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: heltec-v3-firmware-ru
          path: |
            firmware/.pio/build/heltec-v3/firmware*.bin
