name: Build Stable Meshtastic Heltec V3 OLED_RU (on upstream release)

on:
  workflow_dispatch:     # Manual trigger for testing
  repository_dispatch:   # Optional external trigger
    types: [meshtastic-release]
  schedule:
    - cron: "0 2 * * *"  # Fallback: run daily to check for new releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: |
          pip install -U pip
          pip install platformio

      - name: Fetch latest Meshtastic release
        id: get_release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/meshtastic/firmware/releases/latest | jq -r .tag_name)
          echo "Latest Meshtastic release: $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Clone Meshtastic firmware at latest release
        run: |
          git clone --depth=1 --branch ${{ steps.get_release.outputs.tag }} https://github.com/meshtastic/firmware.git
          cd firmware
          git submodule update --init --recursive

      - name: Patch platformio.ini for OLED_RU
        run: |
          sed -i '/-I variants\/esp32s3\/heltec_v3/a\  -D OLED_RU' variants/esp32s3/heltec_v3/platformio.ini
      
      - name: Build Heltec V3 firmware
        run: |
          cd firmware
          pio run -e heltec-v3

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: heltec-v3-${{ steps.get_release.outputs.tag }}-ru
          path: |
            firmware/.pio/build/heltec-v3/firmware*.bin
